spring.application.name=Stripe-Provider-Service

server.port=${SERVER_PORT:1111}

stripe.apiKey=${STRIPE_API_KEY}
stripe.createOrderUrl=${STRIPE_CREATE_ORDER_URL}
stripe.confirmOrderUrl=${STRIPE_CONFIRM_ORDER_URL}

eureka.client.service-url.defaultZone=http://stripe-service-registry:3333/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true