spring.application.name=Stripe-Provider-Service

server.port=${SERVER_PORT:1111}

stripe.apiKey=${STRIPE_API_KEY}
stripe.createOrderUrl=${STRIPE_CREATE_ORDER_URL}
stripe.confirmOrderUrl=${STRIPE_CONFIRM_ORDER_URL}

eureka.client.service-url.defaultZone=https://stripe-service-registry.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

# Prevent premature eviction due to Render pauses / GC
eureka.instance.lease-renewal-interval-in-seconds=20
eureka.instance.lease-expiration-duration-in-seconds=180

